### ISSUE TITLE
spring(app)からmysqlへアクセスできていない

### ISSUE THREAD

**Issue by kousuketk** [kousuketk/backend_java#1]
# docker-composeからmysqlは立ってるが、spring(app)からmysqlとの通信はできていない

## 前提
- docker-composeで立ち上げたmysqlのデータは以下のようになっている
```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sample_db2         |
| sys                |
+--------------------+
6 rows in set (0.05 sec)

mysql> use sample_db2
Database changed
mysql> show tables;
+----------------------+
| Tables_in_sample_db2 |
+----------------------+
| users                |
+----------------------+
1 row in set (0.00 sec)

mysql> select * from users;
+----+------------+---------------------+
| id | name       | email               |
+----+------------+---------------------+
|  1 | test_user1 | test_user1@test.com |
|  2 | test_user2 | test_user2@test.com |
|  3 | test_user3 | test_user3@test.com |
|  4 | test_user4 | test_user4@test.com |
+----+------------+---------------------+
4 rows in set (0.00 sec)
```
- sample_db2を使用して、usersテーブルのuserをCRUD操作したいけど、できない.....
- dockerではmysqlは正常に動いてるからspringからmysqlに接続する所ができていない...
↓以下解決しようとしたこと↓
(curlコマンドで最後に"| jq ." とあるが、これはjsonを見やすくするためのもの。)

### 解決策1
1. 普通に立ち上げる→指定のmysqlを見ていないが、指定のmysqlではないところに、saveされていて、その結果も返ってくる。
- user一覧を返すapiを叩いても、userは返ってこない(mysqlに接続できてないから)
```
$ curl http://localhost:8080/users | jq . 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     2    0     2    0     0    142      0 --:--:-- --:--:-- --:--:--   142
[]
```

- userをcreateできる。(これはどこに保存しているのか？mysqlに保存できていないから、多分一時的にどっかに保存している。)
```
$ curl http://localhost:8080/user/post -X POST -H 'Content-Type: application/json' -d '{"id":7,"name":"test_user1","email":"eeee@email.com"}' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   106    0    53  100    53    103    103 --:--:-- --:--:-- --:--:--   206
{
  "id": 1,
  "name": "test_user1",
  "email": "eeee@email.com"
}
```

- 先程createしたユーザーが保存されていることがわかる(どこに保存されたんだ....???)
```
$ curl http://localhost:8080/users | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    55    0    55    0     0    268      0 --:--:-- --:--:-- --:--:--   266
[
  {
    "id": 1,
    "name": "test_user1",
    "email": "eeee@email.com"
  }
]
```

- 適当にユーザを増やしてみても保存されていることがわかる(どこに保存されてるんだ....???)
```
$ curl http://localhost:8080/user/post -X POST -H 'Content-Type: application/json' -d '{"id":7,"name":"test_user1","email":"eeee@email.com"}' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   106    0    53  100    53    257    257 --:--:-- --:--:-- --:--:--   514
{
  "id": 1,
  "name": "test_user1",
  "email": "eeee@email.com"
}
$ curl http://localhost:8080/user/post -X POST -H 'Content-Type: application/json' -d '{"id":7,"name":"test_user1","email":"eeee@email.com"}' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   106    0    53  100    53   2944   2944 --:--:-- --:--:-- --:--:--  5888
{
  "id": 2,
  "name": "test_user1",
  "email": "eeee@email.com"
}
$ curl http://localhost:8080/user/post -X POST -H 'Content-Type: application/json' -d '{"id":7,"name":"test_user1","email":"eeee@email.com"}' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   106    0    53  100    53   2944   2944 --:--:-- --:--:-- --:--:--  5888
{
  "id": 3,
  "name": "test_user1",
  "email": "eeee@email.com"
}
$ curl http://localhost:8080/users | jq .  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   163    0   163    0     0   6269      0 --:--:-- --:--:-- --:--:--  6520
[
  {
    "id": 1,
    "name": "test_user1",
    "email": "eeee@email.com"
  },
  {
    "id": 2,
    "name": "test_user1",
    "email": "eeee@email.com"
  },
  {
    "id": 3,
    "name": "test_user1",
    "email": "eeee@email.com"
  }
]
```

### 解決策2
- application.propertiesの場所を変更する(configフォルダを作る)→解決策1と同じ

### 解決策3
- 実行時にapplication.propertiesを指定する→buildはできるが、実行するとエラー
```
java -jar build/libs/api-0.0.1-SNAPSHOT.jar --spring.datasource.driver-class-name=com.mysql.jdbc.Driver --spring.datasource.url=jdbc:mysql://localhost:3306/sample_db2?serverTimezone=JST --spring.profiles=localhost --spring.datasource.username=root --spring.datasource.password=rootpass --spring.jpa.database=MYSQL
```
→以下のようにHikaripoolのエラーが出る(mysqlとうまくコネクションできていない)
```
2021-06-15 02:07:39.653 ERROR 1073 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
```
→/usersや/user/postにアクセスするとinternail server errorが返ってくる

## 結論
おそらくapplication.propertiesがうまく設定できていなく、mysqlとコネクションできていないんだけど、どこをどうすれば良いのかわからず。。。。
公式ドキュメント見たりして、application.propertiesの位置を変えたり、実行時に環境を指定してもエラーになったから、手詰まり感....

**Comment by kousuketk** [comment]
dependenciesの、com.h2database:h2が一時的なdbとして動いていたみたいだったから、これを消した。
まだエラーが出てて、解決していないが、一旦mysqlはlocalで動かしてconnectしてみる
```
2021-06-16 10:41:57.059  INFO 222 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-06-16 10:41:58.339 ERROR 222 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.25.jar!/:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.25.jar!/:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) ~[mysql-connector-java-8.0.25.jar!/:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar!/:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar!/:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar!/:8.0.25]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar!/:na]
```_

**Comment by kousuketk** [comment]
JDBC connection protocol - https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html
application.properties - https://docs.spring.io/spring-boot/docs/2.1.7.RELEASE/reference/html/common-application-properties.html
